spring:
  data:
    rest:
      base-path: /rest
  jpa.properties.jadira.usertype.autoRegisterUserTypes: true
  #jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
  jackson.mapper.default-view-inclusion: true
  jackson.serialization.fail-on-empty-beans: false
  datasource:
    url: "jdbc:mysql://localhost:3306/habib"
    username: devuser
    password: dev@password
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    #properties:
      #hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      #hibernate.cache.use_second_level_cache: true
      #hibernate.cache.use_query_cache: true
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none