server:
  port: 8090
spring:
  application:
    name: habibapi
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
  profiles:
    active: localdb
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

upload:
  path: /Users/chadirahme/IdeaProjects/habib-api/suppliers

  #multipart.max-file-size=100MB